In [ ]:
import numpy as np


In [ ]:
vektor = np.array([1,2,3,4,5,6,7,8,14,51,325,2141,231])

In [ ]:
vektor[1:3]

array([2, 3])

In [ ]:
vektor[1:5]

array([2, 3, 4, 5])

In [ ]:
vektor[:5
       ]

array([1, 2, 3, 4, 5])

In [ ]:
vektor[2:6:2
      ]

array([3, 5])

In [ ]:
vektor = np.array([1,2,3,4,5,6])
matris = np.array([[1,2,3],[4,5,6],[7,8,9]])

matris.size


9

In [ ]:
vektor.shape


(6,)

In [ ]:
matris.shape

(3, 3)

In [ ]:
vektor.ndim

1

In [ ]:
matris.ndim

2

In [ ]:
vektor.dtype

dtype('int64')

In [ ]:
matris.dtype

dtype('int64')

In [ ]:
sayilar = np.array([1,2,3,4,5,6])

In [ ]:
sayilar.dtype

dtype('int64')

In [ ]:
sayilar = np.array([1,2,3,4,5.0,6])

In [ ]:
sayilar.dtype

dtype('float64')

In [ ]:
sayilar = np.array([1,2,3,4,5.0,6])
sayilar = sayilar.astype("int8")
sayilar.dtype

dtype('int8')

In [ ]:
sayilar = np.array([1,2,3,4,5,6],dtype="int8")
sayilar.dtype

dtype('int8')

In [ ]:
matris =np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
matris

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [ ]:
matris[0
       ]

array([1, 2, 3, 4])

In [ ]:
matris[-2]

array([ 9, 10, 11, 12])

In [ ]:
matris[1:3]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
matris

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [ ]:
matris[0,:2]

array([1, 2])

In [ ]:
np.random

<module 'numpy.random' from '/usr/local/lib/python3.10/dist-packages/numpy/random/__init__.py'>

In [ ]:
np.random.randint(0,5,(4,4))

array([[0, 1, 4, 1],
       [2, 3, 1, 4],
       [0, 1, 1, 4],
       [4, 4, 0, 1]])

In [ ]:
milyon = np.arange(1000000)
milyon

array([     0,      1,      2, ..., 999997, 999998, 999999])

In [ ]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
np.arange(0,1000000,5)

array([     0,      5,     10, ..., 999985, 999990, 999995])

In [ ]:
m1 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
m1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
m1.shape

(3, 4)

In [ ]:
m1.size

12

In [ ]:
m1.reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
m1.reshape(12,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [ ]:
matris = np.random.randint(0,5,(4,4))

In [ ]:
matris


array([[4, 1, 1, 0],
       [1, 3, 2, 2],
       [3, 1, 0, 0],
       [4, 0, 0, 4]])

In [ ]:
matris2 = matris.view()
matris2

array([[4, 1, 1, 0],
       [1, 3, 2, 2],
       [3, 1, 0, 0],
       [4, 0, 0, 4]])

In [ ]:
matris2[0] = [1,1,1,1]
matris2


array([[1, 1, 1, 1],
       [1, 3, 2, 2],
       [3, 1, 0, 0],
       [4, 0, 0, 4]])

In [ ]:
matris

array([[1, 1, 1, 1],
       [1, 3, 2, 2],
       [3, 1, 0, 0],
       [4, 0, 0, 4]])

In [ ]:
matris3 = np.random.randint(0,5,(4,4))
matris3

array([[4, 1, 3, 4],
       [3, 2, 4, 0],
       [4, 4, 3, 3],
       [4, 1, 2, 3]])

In [ ]:
matris4 = matris3.copy()
matris4

array([[4, 1, 3, 4],
       [3, 2, 4, 0],
       [4, 4, 3, 3],
       [4, 1, 2, 3]])

In [ ]:
matris4[0] = [7,7,7,7]

NameError: ignored

In [ ]:
matris3

array([[4, 1, 3, 4],
       [3, 2, 4, 0],
       [4, 4, 3, 3],
       [4, 1, 2, 3]])

In [ ]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [ ]:
np.ones(shape=(3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.full((4,4),19)

array([[19, 19, 19, 19],
       [19, 19, 19, 19],
       [19, 19, 19, 19],
       [19, 19, 19, 19]])

In [ ]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])