In [1]:
import numpy as np

##arange

In [3]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [4]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

##zeros

In [6]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [8]:
np.zeros((9,9))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [9]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [10]:
np.ones(3)

array([1., 1., 1.])

##linspace

In [11]:
np.linspace(0,20,5)

array([ 0.,  5., 10., 15., 20.])

In [13]:
np.linspace(0,20,3)

array([ 0., 10., 20.])

In [14]:
np.linspace(0,10,24)

array([ 0.        ,  0.43478261,  0.86956522,  1.30434783,  1.73913043,
        2.17391304,  2.60869565,  3.04347826,  3.47826087,  3.91304348,
        4.34782609,  4.7826087 ,  5.2173913 ,  5.65217391,  6.08695652,
        6.52173913,  6.95652174,  7.39130435,  7.82608696,  8.26086957,
        8.69565217,  9.13043478,  9.56521739, 10.        ])

In [15]:
a = np.linspace(0,10,24)

In [16]:
a[2] - a[1]

0.43478260869565216

In [17]:
a[3] - a[2]

0.4347826086956522

##eye

In [18]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [19]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

## random

In [21]:
np.random.randn(4)

array([-1.17426468,  1.09115428, -2.27650406,  1.03014843])

In [23]:
np.random.randn(4,4)

array([[ 0.14887694,  0.31733816,  1.2802928 , -0.97771649],
       [-0.3088662 , -0.25013284, -1.10763693,  0.84284558],
       [ 0.13442226,  1.69151359,  1.85828879,  0.41068284],
       [ 0.10020118, -0.79182913, -0.9488102 ,  0.57177523]])

In [28]:
np.random.randint(5,10)

7

In [29]:
np.random.randint(1,10,5)

array([8, 6, 7, 1, 8])

##numpy dizi methodları

In [31]:
x = np.arange(30)

In [33]:
x.reshape(6,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [34]:
x.max()

29

In [35]:
x.min()

0

In [37]:
x.argmax()

29

In [38]:
x.argmin()

0