In [1]:
import numpy as np

In [2]:
x = np.arange(0,15)

In [3]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [4]:
type(x)

numpy.ndarray

In [5]:
x[3]

3

In [6]:
x[2:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [7]:
x[:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [8]:
x[::-1]

array([14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [9]:
x[3:5]

array([3, 4])

In [11]:
x[3:8]

array([3, 4, 5, 6, 7])

In [12]:
x[3:8] = -5

In [13]:
x

array([ 0,  1,  2, -5, -5, -5, -5, -5,  8,  9, 10, 11, 12, 13, 14])

In [14]:
y = np.arange(0,24)

In [15]:
y

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [19]:
slicindizisi = y[4:9]

In [20]:
slicindizisi

array([4, 5, 6, 7, 8])

In [21]:
slicindizisi = 700

In [22]:
slicindizisi

700