##matrix

In [3]:
import numpy as np

In [4]:
liste = [[10,20,30],[20,30,40],[30,40,50]]

In [5]:
matrix = np.array(liste)

In [6]:
matrix

array([[10, 20, 30],
       [20, 30, 40],
       [30, 40, 50]])

In [7]:
matrix[0]

array([10, 20, 30])

In [8]:
matrix[1][2]

40

In [9]:
matrix[0,1]

20

In [10]:
matrix[1:,2]

array([40, 50])

##operasyon


In [14]:
yenidizi = np.random.randint(1,100,20)

In [16]:
yenidizi

array([88, 24, 95, 53, 78, 22,  9, 17, 42, 47, 67, 98, 24, 53, 32, 34, 97,
       37, 52, 43])

In [17]:
yenidizi > 24

array([ True, False,  True,  True,  True, False, False, False,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
        True,  True])

In [21]:
over24 = []
for i in yenidizi:
  if i > 24:
    over24.append(i)

In [22]:
over24

[88, 95, 53, 78, 42, 47, 67, 98, 53, 32, 34, 97, 37, 52, 43]

In [23]:
sonDizi = np.arange(0,24)
sonDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [24]:
sonDizi+ sonDizi

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46])

In [25]:
sonDizi- sonDizi

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [26]:
sonDizi * sonDizi

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529])

In [27]:
sonDizi / sonDizi

<ipython-input-27-20a5ae775714>:1: RuntimeWarning: invalid value encountered in divide
  sonDizi / sonDizi


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [28]:
np.sqrt(sonDizi)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595, 4.58257569, 4.69041576, 4.79583152])